# ✨ Release Boss Configuration ✨
# This fabulous YAML config file controls how the Release Boss behaves!
# Feel free to customize it to match your project's needs 💅

# Branch Configuration
# -------------------
mergeBranch: main        # Branch where changes are merged
stagingBranch: staging   # Prefix for staging branches
releaseBranch: release   # Branch where releases are created

# PR Configuration
# ---------------
pullRequestTitle: "chore: release ✨ {version} ✨"  # Title format for release PRs
pullRequestHeader: "# 🎉 Release Time! 💃"         # Header text for PR description

# Version Files
# ------------
versionFiles: []  # Files that should be updated with the new version number

# Template Files
# -------------
templateFiles:     # Files that should be processed with version variables
  - src/version.tpl.js

# Update Files
# ------------
updateFiles:
  - file: package.json
    findLine: "  \"version\": "
    replaceLine: "  \"version\": \"{version}\","

# Changelog Configuration
# ---------------------
changelogPath: CHANGELOG.md  # Where to write the changelog

# Customize how different commit types appear in the changelog
changelogSections:
  - type: feat
    section: "✨ Fabulous New Features ✨"
    hidden: false
  
  - type: fix
    section: "🛠️ Bug Fixes & Polish 💅"
    hidden: false
    
  - type: perf
    section: "⚡ Performance Slayage 🔥"
    hidden: false
    
  - type: refactor
    section: "💃 Code Makeovers 💋"
    hidden: false
    
  - type: docs
    section: "📝 Documentation Glow-Ups 📚"
    hidden: false
    
# PR-Based Changelog Table Configuration
# ------------------------------------
changelogTable:
  enabled: true  # Enable the PR-based changelog table
  
  # HTML comment markers to identify the table
  markers:
    start: "<!-- RELEASE_BOSS_CHANGELOG_START -->"
    end: "<!-- RELEASE_BOSS_CHANGELOG_END -->"
    
  # Table columns configuration
  columns:
    - name: "Type"
      field: "type"
    - name: "Scope"
      field: "scope"
    - name: "Description"
      field: "description"
    - name: "PR"
      field: "pr"
    - name: "Commit"
      field: "commit"
    - name: "Author"
      field: "author"
      
  # Sorting options
  sorting:
    enabled: true
    order: 
      - feat
      - fix
      - perf
      - refactor
      - docs
      - test
      - ci
      - build
      - chore
    
  # Filtering options
  filtering:
    excludeTypes: 
      - chore  # Commit types to exclude from changelog table
    requireScope: false       # Whether to require a scope for all entries

# Tagging Configuration
# -------------------
versionTagPrefix: true  # Whether to prefix tags with 'v' (e.g., v1.0.0)
tagLatest: true         # Whether to update the 'latest' tag
tagMajor: true          # Whether to tag major versions (e.g., v1)
tagMinor: true          # Whether to tag minor versions (e.g., v1.0)
