name: Release with PR Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Release Boss with PR Changelog
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ github.event.inputs.version || '' }}
          config-path: '.release-boss.yml'
        env:
          # Enable debug logging
          DEBUG: 'release-boss:*'
